"""Фаза 3: предупреждения проверки и автор загрузки у версий шаблонов ТЗ

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 09:37:00.597924
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_versions', sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('template_versions', sa.Column('uploaded_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_template_versions_uploaded_by_users'), 'template_versions', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_template_versions_uploaded_by_users'), 'template_versions', type_='foreignkey')
    op.drop_column('template_versions', 'uploaded_by')
    op.drop_column('template_versions', 'warnings_json')
    # ### end Alembic commands ###
